name: halos
channels:
  - nvidia/label/cuda-12.1.1
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2023.7.22=hbcca054_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.1.0=he5830b7_0
  - libgomp=13.1.0=he5830b7_0
  - libnsl=2.0.0=h7f98852_0
  - libsqlite=3.42.0=h2797004_0
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - ncurses=6.4=hcb278e6_0
  - openssl=3.1.2=hd590300_0
  - pip=23.2.1=pyhd8ed1ab_0
  - python=3.10.12=hd12c33a_0_cpython
  - readline=8.2=h8228510_1
  - setuptools=68.0.0=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - wheel=0.41.1=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - accelerate==0.21.0
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - alpaca-eval==0.3.6
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.2.0
      - appdirs==1.4.4
      - asttokens==2.2.1
      - async-timeout==4.0.3
      - attrs==23.1.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.2
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - click==8.1.6
      - cmake==3.27.1
      - comm==0.1.4
      - contourpy==1.1.0
      - cycler==0.11.0
      - datasets==2.12.0
      - debugpy==1.6.7.post1
      - decorator==5.1.1
      - dill==0.3.6
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.15
      - einops==0.7.0
      - exceptiongroup==1.2.0
      - executing==1.2.0
      - fasttext==0.9.2
      - filelock==3.12.2
      - fire==0.5.0
      - flash-attn==2.3.3
      - fonttools==4.42.1
      - frozenlist==1.4.0
      - fsspec==2023.6.0
      - gitdb==4.0.10
      - gitpython==3.1.32
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - huggingface-hub==0.16.4
      - hydra-core==1.3.2
      - idna==3.4
      - ipykernel==6.23.1
      - ipython==8.14.0
      - jedi==0.19.0
      - jinja2==3.1.2
      - jupyter-client==8.3.0
      - jupyter-core==5.3.1
      - kiwisolver==1.4.5
      - lit==16.0.6
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.0.4
      - multiprocess==0.70.14
      - nest-asyncio==1.5.7
      - networkx==3.1
      - ninja==1.11.1.1
      - numpy==1.24.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.3.101
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - openai==1.6.1
      - packaging==23.1
      - pandas==2.0.3
      - parso==0.8.3
      - pathtools==0.1.2
      - patsy==0.5.3
      - peft==0.4.0
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.0
      - platformdirs==3.10.0
      - prompt-toolkit==3.0.39
      - protobuf==4.24.0
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyarrow==12.0.1
      - pybind11==2.11.1
      - pydantic==2.5.3
      - pydantic-core==2.14.6
      - pygments==2.16.1
      - pyparsing==3.0.9
      - python-dateutil==2.8.2
      - python-dotenv==1.0.0
      - pytz==2023.3
      - pyyaml==6.0.1
      - pyzmq==25.1.1
      - regex==2023.8.8
      - requests==2.31.0
      - responses==0.18.0
      - rich==13.6.0
      - safetensors==0.3.2
      - scipy==1.11.2
      - sentencepiece==0.1.99
      - sentry-sdk==1.29.2
      - setproctitle==1.3.2
      - shtab==1.6.4
      - six==1.16.0
      - smmap==5.0.0
      - sniffio==1.3.0
      - soupsieve==2.4.1
      - stack-data==0.6.2
      - statsmodels==0.14.0
      - sympy==1.12
      - tensor-parallel==1.2.4
      - termcolor==2.3.0
      - tiktoken==0.5.1
      - tokenizers==0.15.0
      - torch==2.1.1
      - tornado==6.3.3
      - tqdm==4.65.0
      - traitlets==5.9.0
      - transformers==4.35.2
      - triton==2.1.0
      - trl==0.7.2
      - typing-extensions==4.7.1
      - tyro==0.5.10
      - tzdata==2023.3
      - urllib3==2.0.4
      - wandb==0.15.3
      - wcwidth==0.2.6
      - xxhash==3.3.0
      - yarl==1.9.2