name: halos_v2
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - blas=2.116=mkl
  - blas-devel=3.9.0=16_linux64_mkl
  - brotli-python=1.1.0=py312h30efb56_1
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.2.2=hbcca054_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - cuda-cudart=12.1.105=0
  - cuda-cupti=12.1.105=0
  - cuda-libraries=12.1.0=0
  - cuda-nvrtc=12.1.105=0
  - cuda-nvtx=12.1.105=0
  - cuda-opencl=12.3.101=0
  - cuda-runtime=12.1.0=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=pyhd8ed1ab_0
  - freetype=2.12.1=h267a509_2
  - gmp=6.3.0=h59595ed_0
  - gnutls=3.6.13=h85f3911_1
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - lame=3.100=h166bdaf_1003
  - lcms2=2.15=hfd0df8a_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libblas=3.9.0=16_linux64_mkl
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.1.0.26=0
  - libcufft=11.0.2.4=0
  - libcufile=1.8.1.2=0
  - libcurand=10.3.4.107=0
  - libcusolver=11.4.4.55=0
  - libcusparse=12.0.2.55=0
  - libdeflate=1.17=h0b41bf4_0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=2.0.0=h9bf148f_0
  - liblapack=3.9.0=16_linux64_mkl
  - liblapacke=3.9.0=16_linux64_mkl
  - libnpp=12.0.2.50=0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.1.105=0
  - libnvjpeg=12.1.1.14=0
  - libpng=1.6.42=h2797004_0
  - libsqlite=3.45.1=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libtiff=4.5.0=h6adf6a1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.5=h232c23b_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=15.0.7=h0cdce71_0
  - markupsafe=2.1.5=py312h98912ed_0
  - mkl=2022.1.0=h84fe81f_915
  - mkl-devel=2022.1.0=ha770c72_916
  - mkl-include=2022.1.0=h84fe81f_915
  - mpmath=1.3.0=pyhd8ed1ab_0
  - ncurses=6.4=h59595ed_2
  - nettle=3.6=he412f7d_0
  - networkx=3.2.1=pyhd8ed1ab_0
  - numpy=1.26.4=py312heda63a1_0
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.5.0=hfec8fc6_2
  - openssl=3.2.1=hd590300_0
  - pillow=10.2.0=py312h5eee18b_0
  - pip=24.0=pyhd8ed1ab_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.12.1=hab00c5b_1_cpython
  - python_abi=3.12=4_cp312
  - pytorch=2.2.0=py3.12_cuda12.1_cudnn8.9.2_0
  - pytorch-cuda=12.1=ha16c6d3_5
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0.1=py312h98912ed_1
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - setuptools=69.0.3=pyhd8ed1ab_0
  - sympy=1.12=pyh04b8f61_3
  - tbb=2021.11.0=h00ab1b0_1
  - tk=8.6.13=noxft_h4845f30_101
  - torchaudio=2.2.0=py312_cu121
  - torchvision=0.17.0=py312_cu121
  - typing_extensions=4.9.0=pyha770c72_0
  - urllib3=2.2.0=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - accelerate==0.21.0
      - aiohttp==3.9.3
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.2.0
      - appdirs==1.4.4
      - attrs==23.2.0
      - click==8.1.7
      - datasets==2.17.0
      - dill==0.3.6
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - einops==0.7.0
      - flash-attn==2.3.3
      - frozenlist==1.4.1
      - fsspec==2023.10.0
      - gitdb==4.0.11
      - gitpython==3.1.41
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.26.0
      - huggingface-hub==0.20.3
      - hydra-core==1.3.2
      - multidict==6.0.5
      - multiprocess==0.70.14
      - ninja==1.11.1.1
      - omegaconf==2.3.0
      - openai==1.12.0
      - packaging==23.2
      - pandas==2.2.0
      - protobuf==4.25.2
      - psutil==5.9.8
      - pyarrow==15.0.0
      - pyarrow-hotfix==0.6
      - pydantic==2.6.1
      - pydantic-core==2.16.2
      - python-dateutil==2.8.2
      - pytz==2024.1
      - regex==2023.12.25
      - responses==0.18.0
      - safetensors==0.4.2
      - sentry-sdk==1.40.3
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.0
      - tokenizers==0.15.2
      - tqdm==4.66.2
      - transformers==4.35.2
      - tzdata==2024.1
      - wandb==0.16.3
      - xxhash==3.4.1
      - yarl==1.9.4
variables:
  TRANSFORMERS_CACHE: /data/huggingface/hub
  HF_HOME: /data/huggingface/
  HF_DATASETS_CACHE: /data/huggingface/datasets
prefix: /opt/conda/envs/halos3
