# Group Relative Policy Optimization

# the weight placed on the KL penalty
beta: 0.01

# used for clipping the log-ratio, as in PPO
epsilon: 0.01

# whether to use sequence level rewards
sequence_level: true

trainer: GRPOTrainer

dataloader: GroupUnpairedPreferenceDataLoader